package com.springboot.weathersensorapi.model;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Represents a weather metric captured by a sensor.
 * Each instance corresponds to a specific measurement (e.g., temperature, humidity).
 */
@Data
@Entity
@Table(name = "weather_metrics")
public class WeatherModel {

    /**
     * Unique identifier for the metric. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Identifier of the sensor capturing the metric.
     */
    @Column(name = "sensor_id", nullable = false)
    private String sensorId;

    /**
     * Type of metric (e.g., temperature, humidity).
     */
    @Column(nullable = false)
    private String metric;

    /**
     * Numeric value of the metric.
     */
    @Column(nullable = false)
    private Double value;

    /**
     * Timestamp indicating when the metric was captured.
     */
    @Column(nullable = false)
    private LocalDateTime timestamp;

    // Constructors (including a no-arg constructor for JPA)

    public WeatherModel() {
        // Default constructor for JPA
    }

    public WeatherModel(String sensorId, String metric, Double value, LocalDateTime timestamp) {
        this.sensorId = sensorId;
        this.metric = metric;
        this.value = value;
        this.timestamp = timestamp;
    }
}
